"""Standardized 10-category brand profile schema used to normalize
whatever raw information a company provides into one consistent shape."""

CATEGORY_SCHEMA = {
    "type": "object",
    "properties": {
        "business_identity": {
            "type": "object",
            "properties": {
                "company_name": {"type": "string"},
                "industry": {"type": "string"},
                "products_services": {"type": "string"},
                "business_model": {"type": "string"},
                "value_proposition": {"type": "string"},
                "competitive_advantage": {"type": "string"},
            },
            "required": [
                "company_name",
                "industry",
                "products_services",
                "business_model",
                "value_proposition",
                "competitive_advantage",
            ],
            "additionalProperties": False,
        },
        "brand_personality": {
            "type": "object",
            "properties": {
                "tone_of_voice": {"type": "string"},
                "personality": {"type": "string"},
                "communication_style": {"type": "string"},
                "words_to_use": {"type": "array", "items": {"type": "string"}},
                "words_to_avoid": {"type": "array", "items": {"type": "string"}},
            },
            "required": [
                "tone_of_voice",
                "personality",
                "communication_style",
                "words_to_use",
                "words_to_avoid",
            ],
            "additionalProperties": False,
        },
        "target_audience": {
            "type": "object",
            "properties": {
                "demographics": {"type": "string"},
                "pain_points": {"type": "array", "items": {"type": "string"}},
                "goals": {"type": "array", "items": {"type": "string"}},
                "motivations": {"type": "array", "items": {"type": "string"}},
                "buying_triggers": {"type": "array", "items": {"type": "string"}},
                "objections": {"type": "array", "items": {"type": "string"}},
                "interests": {"type": "array", "items": {"type": "string"}},
            },
            "required": [
                "demographics",
                "pain_points",
                "goals",
                "motivations",
                "buying_triggers",
                "objections",
                "interests",
            ],
            "additionalProperties": False,
        },
        "business_goals": {
            "type": "object",
            "properties": {
                "brand_awareness": {"type": "string"},
                "leads": {"type": "string"},
                "sales": {"type": "string"},
                "community": {"type": "string"},
                "education": {"type": "string"},
                "retention": {"type": "string"},
            },
            "required": [
                "brand_awareness",
                "leads",
                "sales",
                "community",
                "education",
                "retention",
            ],
            "additionalProperties": False,
        },
        "content_strategy": {
            "type": "object",
            "properties": {
                "content_pillars": {"type": "array", "items": {"type": "string"}},
                "preferred_formats": {"type": "array", "items": {"type": "string"}},
                "platforms": {"type": "array", "items": {"type": "string"}},
                "posting_frequency": {"type": "string"},
                "topics": {"type": "array", "items": {"type": "string"}},
                "content_to_avoid": {"type": "array", "items": {"type": "string"}},
            },
            "required": [
                "content_pillars",
                "preferred_formats",
                "platforms",
                "posting_frequency",
                "topics",
                "content_to_avoid",
            ],
            "additionalProperties": False,
        },
        "brand_assets": {
            "type": "object",
            "properties": {
                "website": {"type": "string"},
                "brand_guidelines": {"type": "string"},
                "colors": {"type": "array", "items": {"type": "string"}},
                "logo": {"type": "string"},
                "slogan": {"type": "string"},
                "existing_captions": {"type": "array", "items": {"type": "string"}},
                "best_performing_posts": {"type": "array", "items": {"type": "string"}},
            },
            "required": [
                "website",
                "brand_guidelines",
                "colors",
                "logo",
                "slogan",
                "existing_captions",
                "best_performing_posts",
            ],
            "additionalProperties": False,
        },
        "social_performance": {
            "type": "object",
            "properties": {
                "best_posts": {"type": "array", "items": {"type": "string"}},
                "worst_posts": {"type": "array", "items": {"type": "string"}},
                "viral_content": {"type": "string"},
                "average_engagement": {"type": "string"},
            },
            "required": [
                "best_posts",
                "worst_posts",
                "viral_content",
                "average_engagement",
            ],
            "additionalProperties": False,
        },
        "competitor_context": {
            "type": "object",
            "properties": {
                "main_competitors": {"type": "array", "items": {"type": "string"}},
                "market_positioning": {"type": "string"},
                "opportunities": {"type": "array", "items": {"type": "string"}},
                "trends": {"type": "array", "items": {"type": "string"}},
            },
            "required": [
                "main_competitors",
                "market_positioning",
                "opportunities",
                "trends",
            ],
            "additionalProperties": False,
        },
        "campaign_context": {"type": "string"},
        "constraints": {
            "type": "object",
            "properties": {
                "legal_restrictions": {"type": "string"},
                "mandatory_cta": {"type": "string"},
                "forbidden_claims": {"type": "array", "items": {"type": "string"}},
                "brand_rules": {"type": "array", "items": {"type": "string"}},
                "maximum_duration": {"type": "string"},
                "platform": {"type": "array", "items": {"type": "string"}},
            },
            "required": [
                "legal_restrictions",
                "mandatory_cta",
                "forbidden_claims",
                "brand_rules",
                "maximum_duration",
                "platform",
            ],
            "additionalProperties": False,
        },
    },
    "required": [
        "business_identity",
        "brand_personality",
        "target_audience",
        "business_goals",
        "content_strategy",
        "brand_assets",
        "social_performance",
        "competitor_context",
        "campaign_context",
        "constraints",
    ],
    "additionalProperties": False,
}

# (key, display label) pairs, in the fixed presentation order — drives the UI.
CATEGORY_LABELS = [
    ("business_identity", "1. Business Identity"),
    ("brand_personality", "2. Brand Personality"),
    ("target_audience", "3. Target Audience"),
    ("business_goals", "4. Business Goals"),
    ("content_strategy", "5. Content Strategy"),
    ("brand_assets", "6. Brand Assets"),
    ("social_performance", "7. Social Performance"),
    ("competitor_context", "8. Competitor Context"),
    ("campaign_context", "9. Campaign Context"),
    ("constraints", "10. Constraints"),
]
